### ISSUE TITLE
Support for NG 9

### ISSUE THREAD

**Issue by juan-fdz-hawa** [mobxjs/mobx-angular#110]
Hi,

Excellent work with mobx-angular!

I was wondering if there are any plans for supporting NG 9 soon? If nothing is planned ATM, maybe I can help you guys with that :)?

Thanks

**Comment by kubk** [comment]
Hi @juan-fdz-hawa 
I am using mobx-angular extensively on production (with NG 7) and on a pet project with NG 9 (release candidate, because it is not released yet) and didn't encounter any issues. But feel free to test it on your own and report any issues.

Hi @adamkleingit 
Travis CI supports build matrix to test a package against different environments, node versions, set of dependencies, etc: https://docs.travis-ci.com/user/build-matrix/
We can test mobx-angular against different angular versions on CI. What are your thoughts on it?

**Comment by juan-fdz-hawa** [comment]
Updating from 3.0.1 to 3.0.3 solved the issue, thanks!

**Comment by adamkleingit** [comment]
@kubk that's a fantastic idea. Do you want to create a PR for this?

**Comment by kubk** [comment]
@adamkleingit Sure, I'll create a PR as soon as I have the time. Thank you.
