### ISSUE TITLE
mobxAngularDebug(true) disables  rxJs stream

### ISSUE THREAD

**Issue by roger-gl** [mobxjs/mobx-angular#64]
this stops working as soon as debug is set to true:

from(toStream( () => this.otherTitle = this.getTitle(), true)).subscribe(l => console.log(l)); 

(toStream is from mobx-utils)

**Comment by adamkleingit** [comment]
Hi,
can you reproduce here:
https://stackblitz.com/edit/angular-usygae?file=app%2Fapp.component.html

**Comment by roger-gl** [comment]
No, because I get: mobxAngularDebug is not defined in the console

**Comment by adamkleingit** [comment]
Yes because you need to click on the "open in new window" button at the top right:
![image](https://user-images.githubusercontent.com/889418/36932397-ffa37c98-1ed0-11e8-8c8d-ee50dad40cc2.png)

And then it's available

**Comment by istiti** [comment]
@adamkleingit i get problem to debug due to `mobxAngularDebug` when i  open devtools it always block at `();` last line of code. I can't debug. verry annoying. 

Can we imagine angular-tree-componentn without 3th party lib ! Everyone will appreciate. 

Already invoke idea here https://github.com/500tech/angular-tree-component/issues/564 but you  seems attached to project you contribute :-)
